#!/bin/bash
#chkconfig: 345 63 37
#description: kibana

path=/app/kibana
stop(){
  is_exist
   if [ $? -eq "0" ]; then
     kill -9 `ps aux | grep kibana| grep -v grep | gawk '{print $2}'`
     echo "kibana is stoping"
   else
     echo "kibana is stoped"
    fi

}

is_exist() {
    pid=`ps -ef| grep kibana | grep -v grep | awk '{print $2}' `
    #如果不存在返回1，存在返回0
    if [ -z "${pid}" ]; then
      return 1
    else
      return 0
    fi
}

start() {
   is_exist
   if [ $? -eq "0" ]; then
     echo "kibana is running. pid=${pid} ."
   else
     nohup $path/bin/kibana --allow-root > /dev/null 2>&1 &
     echo "kibana is starting"
    fi
}

status() {
   is_exist
   if [ $? -eq "0" ]; then
     echo "kibana is running. pid=${pid} ."
   else
     echo "kibana is stop"
   fi
}

case $1 in
   "start")
     start
     ;;
   "stop")
     stop
     ;;
   "status")
     status
     ;;
        *)
        echo "$0 Usage( start | stop | status  )"
        ;;
esac
